def custom_song(name, adjective, animal1, animal2, animal3, noise1, noise2, noise3):
   
   
    print("\n\n")
    print(f"Old {name} had a {adjective} farm. E-I-E-I-O")
    print(f"And on that {adjective} farm he had a {animal1}. E-I-E-I-O")
    print(f"With an {noise1} {noise1} here.")
    print(f"And an {noise1} {noise1} there.")
    print(f"Here an {noise1}.")
    print(f"There an {noise1}.")
    print(f"Everywhere an {noise1} {noise1}.")
    print(f"Old {name} had a {adjective} farm. E-I-E-I-O")
    print()
    print(f"Old {name} had a {adjective} farm. E-I-E-I-O")
    print(f"And on that {adjective} far, he had a {animal2}. E-I-E-I-O")
    print(f"With an {noise2} {noise2} here.")
    print(f"And an {noise2} {noise2} there.")
    print(f"And an {noise1} {noise1} here.")
    print(f"And an {noise1} {noise1} there.")
    print(f"Old {name} had a {adjective} farm. E-I-E-I-O")
    print()
    print(f"Old {name} had a {adjective} farm. E-I-E-I-O")
    print(f"And on that {adjective} farm he had a {animal3}. E-I-E-I-O")
    print(f"With an {noise3} {noise3} here.")
    print(f"And an {noise3} {noise3} there.")
    print(f"And an {noise2} {noise2} here.")
    print(f"And an {noise2} {noise2} there.")
    print(f"And an {noise1} {noise1} here.")
    print(f"And an {noise1} {noise1} there.")
    print(f"Old {name} had a {adjective} farm. E-I-E-I-O")
input_name = input("Enter a name: ")
input_adjective = input("Enter where the farm is: ")
input_animal1 = input("Enter first animal: ")
input_animal2 = input("Enter a second animal: ")
input_animal3 = input("Enter a third animal: ")
input_noise1 = input("Enter a noise for the first animal: ")
input_noise2 = input("Enter a noise for the second animal: ")
input_noise3 = input("Enter a noise for the third animal: ")
custom_song(name=input_name, adjective=input_adjective, animal1=input_animal1, animal2=input_animal2, animal3=input_animal3, noise1=input_noise1, noise2=input_noise2, noise3=input_noise3)  
